#!/bin/bash -e

# ./ngxenv setup | teardown | rebuild | logs | ssh | wireshark | benchmark

eval $(docker-machine env default)

function setup(){
  git clone https://github.com/mikhailov/docker-nginx-amplify.git /tmp/docker-nginx-amplify
  cd /tmp/docker-nginx-amplify && git checkout patch-1 && docker build -t nginx-amplify . && rm -rf /tmp/docker-nginx-amplify
  docker run --net network0 --name nginx -p 80:80 -e API_KEY=$AMPLIFY_API_KEY -d nginx-amplify
}

function rebuild()     { docker cp ./nginx.client.conf nginx:/etc/nginx/nginx.conf; docker restart nginx; logs; }
function configtest()  { docker exec -i -t nginx /bin/bash nginx -t; }
function teardown()    { docker rm -f nginx; }
function ssh()         { docker exec -i -t nginx /bin/bash; }
function logs()        { docker exec -t -t nginx /usr/bin/tail -f /var/log/nginx/access.log; }
function wireshark()   { docker run --rm --net=container:nginx crccheck/tcpdump -i any --immediate-mode -w - | /usr/local/bin/wireshark -k -i -; }

function benchmark()   { 
  siege -b -t 10m http://$(docker-machine ip)/upstream-close/proxy_pass_connection-close/server_keepalive_timeout-0 && \
  sleep 30 && \
  siege -b -t 10m http://$(docker-machine ip)/upstream-close/proxy_pass_connection-keepalive/server_keepalive_timeout-0 && \
  sleep 30 && \
  siege -b -t 10m http://$(docker-machine ip)/upstream-close/proxy_pass_connection-keepalive/server_keepalive_timeout-300 && \
  sleep 30 && \
  siege -b -t 10m http://$(docker-machine ip)/upstream-keepalive/proxy_pass_connection-keepalive/server_keepalive_timeout-0 && \
  sleep 30 && \
  siege -b -t 10m http://$(docker-machine ip)/upstream-keepalive/proxy_pass_connection-keepalive/server_keepalive_timeout-300;
}

case "$1" in
  setup)       setup ;;
  teardown)    teardown ;;
  rebuild)     rebuild ;;
  configtest)  configtest ;;
  ssh)         ssh ;;
  logs)        logs ;;
  wireshark)   wireshark ;;
  benchmark)   benchmark ;;
esac
